In [3]:
# !C:\Users\user\AppData\Local\Programs\Python\Python311\python.exe -m pip install yfinance

In [30]:
### https://github.com/RedaAldahan/Fiancne_Models/blob/main/Dividends_Discount_Model/Dividends_discount_Model(Final).ipynb

### The Formula:

$$
Fair\;Share\;Price = \frac{Expected\;Future\;Dividends}{(Cost\;of\;Equity - Expected\;Growth)}
$$

<center>Formula</center>

$$
Cost\;of\;Equity = Risk\;Free\;Rate + (Beta \times Market\;Premium)
$$

$$
Market\;Premium = Market\;Return - Risk\;Free\;Rate
$$

$$
Risk\;Free\;Rate = 10\;Years\;Treasury\;Yield
$$

$$
Market\;Return = Return\;of\;the\;S\&P\;500
$$

In [2]:
import yfinance as yf # this is to get the stock data
import pandas as pd # this is for working on data frames
import numpy as np # this is to manipulate the data

In [67]:
ticker = yf.Ticker("t") 
# vnindex = yf.Ticker("^VNINDEX.VN")
#vnm = yf.Ticker("VNM.NS") # .NS .HN 
# hist = vnindex.history(period="5d")  # Lấy dữ liệu 1 năm gần nhất
stock = ticker.actions

In [68]:
stock_split = stock["Stock Splits"].to_numpy()
stock_split

array([0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 3.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 2.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 2.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 1.324, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [6]:
stock_split_replaced = np.where(stock_split == 0, 1, stock_split)

array([1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
       1.   , 1.   , 1.   , 1.   , 3.   , 1.   , 1.   , 1.   , 1.   ,
       1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
       1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
       1.   , 2.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
       1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
       1.   , 1.   , 1.   , 2.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
       1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
       1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
       1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
       1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
       1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
       1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
       1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
       1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
       1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
       1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
       1.   , 1.324, 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
       1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ])

In [7]:
stock_split_comp = np.cumprod(stock_split_replaced, axis=0)

array([ 1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,
        1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  3.   ,  3.   ,  3.   ,
        3.   ,  3.   ,  3.   ,  3.   ,  3.   ,  3.   ,  3.   ,  3.   ,
        3.   ,  3.   ,  3.   ,  3.   ,  3.   ,  3.   ,  3.   ,  3.   ,
        3.   ,  3.   ,  3.   ,  3.   ,  3.   ,  6.   ,  6.   ,  6.   ,
        6.   ,  6.   ,  6.   ,  6.   ,  6.   ,  6.   ,  6.   ,  6.   ,
        6.   ,  6.   ,  6.   ,  6.   ,  6.   ,  6.   ,  6.   ,  6.   ,
        6.   , 12.   , 12.   , 12.   , 12.   , 12.   , 12.   , 12.   ,
       12.   , 12.   , 12.   , 12.   , 12.   , 12.   , 12.   , 12.   ,
       12.   , 12.   , 12.   , 12.   , 12.   , 12.   , 12.   , 12.   ,
       12.   , 12.   , 12.   , 12.   , 12.   , 12.   , 12.   , 12.   ,
       12.   , 12.   , 12.   , 12.   , 12.   , 12.   , 12.   , 12.   ,
       12.   , 12.   , 12.   , 12.   , 12.   , 12.   , 12.   , 12.   ,
       12.   , 12.   , 12.   , 12.   , 12.   , 12.   , 12.   , 12.   ,
       12.   , 12.   , 12.   , 12.   , 12.   , 12.   , 12.   , 12.   ,
       12.   , 12.   , 12.   , 12.   , 12.   , 12.   , 12.   , 12.   ,
       12.   , 12.   , 12.   , 12.   , 12.   , 12.   , 12.   , 12.   ,
       12.   , 12.   , 12.   , 12.   , 12.   , 12.   , 12.   , 12.   ,
       12.   , 12.   , 12.   , 12.   , 12.   , 12.   , 12.   , 12.   ,
       12.   , 12.   , 15.888, 15.888, 15.888, 15.888, 15.888, 15.888,
       15.888, 15.888, 15.888, 15.888, 15.888, 15.888, 15.888, 15.888,
       15.888])

In [36]:
stock["stocksplit_adj"] = stock_split_comp.tolist()

In [37]:
stock["div_adj"] = stock["Dividends"] * stock["stocksplit_adj"]
stock

                           Dividends  Stock Splits  stocksplit_adj   div_adj
Date
1984-03-26 00:00:00-05:00   0.116667           0.0           1.000  0.116667
1984-06-25 00:00:00-04:00   0.116667           0.0           1.000  0.116667
1984-09-24 00:00:00-04:00   0.116667           0.0           1.000  0.116667
1985-01-04 00:00:00-05:00   0.116667           0.0           1.000  0.116667
1985-04-03 00:00:00-05:00   0.125000           0.0           1.000  0.125000
...                              ...           ...             ...       ...
2024-07-10 00:00:00-04:00   0.278000           0.0          15.888  4.416864
2024-10-10 00:00:00-04:00   0.278000           0.0          15.888  4.416864
2025-01-10 00:00:00-05:00   0.278000           0.0          15.888  4.416864
2025-04-10 00:00:00-04:00   0.278000           0.0          15.888  4.416864
2025-07-10 00:00:00-04:00   0.278000           0.0          15.888  4.416864

[169 rows x 4 columns]

In [38]:
stock['year'] = stock.index.year
stock_grp = stock.groupby(by=["year"]).sum()
stock_grp.tail(20)

      Dividends  Stock Splits  stocksplit_adj    div_adj
year
2006      1.332         0.000          48.000  15.984000
2007      1.420         0.000          48.000  17.040000
2008      1.600         0.000          48.000  19.200000
2009      1.640         0.000          48.000  19.680000
2010      1.680         0.000          48.000  20.160000
2011      1.720         0.000          48.000  20.640000
2012      1.760         0.000          48.000  21.120000
2013      1.800         0.000          48.000  21.600000
2014      1.840         0.000          48.000  22.080000
2015      1.880         0.000          48.000  22.560000
2016      1.920         0.000          48.000  23.040000
2017      1.960         0.000          48.000  23.520000
2018      2.000         0.000          48.000  24.000000
2019      2.040         0.000          48.000  24.480000
2020      2.080         0.000          48.000  24.960000
2021      2.080         0.000          48.000  24.960000
2022      1.354         1.324          75.552  19.490592
2023      1.112         0.000          63.552  17.667456
2024      1.112         0.000          63.552  17.667456
2025      0.834         0.000          47.664  13.250592

In [39]:
stock_grp["div_PCT_Change"] = stock_grp["div_adj"].pct_change(fill_method ='ffill')
stock_grp.tail(20)

C:\Users\user\AppData\Local\Temp\ipykernel_11016\1743223980.py:1: FutureWarning: The 'fill_method' keyword being not None and the 'limit' keyword in Series.pct_change are deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  stock_grp["div_PCT_Change"] = stock_grp["div_adj"].pct_change(fill_method ='ffill')

      Dividends  Stock Splits  stocksplit_adj    div_adj  div_PCT_Change
year
2006      1.332         0.000          48.000  15.984000        0.030960
2007      1.420         0.000          48.000  17.040000        0.066066
2008      1.600         0.000          48.000  19.200000        0.126761
2009      1.640         0.000          48.000  19.680000        0.025000
2010      1.680         0.000          48.000  20.160000        0.024390
2011      1.720         0.000          48.000  20.640000        0.023810
2012      1.760         0.000          48.000  21.120000        0.023256
2013      1.800         0.000          48.000  21.600000        0.022727
2014      1.840         0.000          48.000  22.080000        0.022222
2015      1.880         0.000          48.000  22.560000        0.021739
2016      1.920         0.000          48.000  23.040000        0.021277
2017      1.960         0.000          48.000  23.520000        0.020833
2018      2.000         0.000          48.000  24.000000        0.020408
2019      2.040         0.000          48.000  24.480000        0.020000
2020      2.080         0.000          48.000  24.960000        0.019608
2021      2.080         0.000          48.000  24.960000        0.000000
2022      1.354         1.324          75.552  19.490592       -0.219127
2023      1.112         0.000          63.552  17.667456       -0.093539
2024      1.112         0.000          63.552  17.667456        0.000000
2025      0.834         0.000          47.664  13.250592       -0.250000

In [43]:
median_growth = stock_grp["div_PCT_Change"].median()
median_growth

0.03095975232198156

In [44]:
lst_Div = stock_grp.at[2025,'Dividends']
lst_Div

0.8340000000000001

In [45]:
exp_future_div = round(lst_Div * (1 + median_growth),2)
exp_future_div

0.86

In [46]:
# If you want to use the 10 year treasury yield today use this code
# bond = yf.Ticker("^TNX")
# hist = bond.history(period="today")
# risk_free_rate = round(hist.iloc[0]['Close']/100,4)
# risk_free_rate

In [48]:
risk_free_rate = 0.03
# assume the avg return for sp500 = 11%
mkt_return = .11
MKT_Risk_prem = mkt_return - risk_free_rate
MKT_Risk_prem

beta = ticker.info["beta"]
beta

# cost of equity
COE = round(beta * MKT_Risk_prem + risk_free_rate,4)
print(f"COE: {COE}")

#
fair_sharePrice = round(exp_future_div/(COE-median_growth),2)
fair_sharePrice
print(f"fair_sharePrice: {fair_sharePrice}")

#
stock_price = ticker.history(period="1d")
stock_price_close = round(stock_price.iloc[0]['Close'],4)
stock_price_close
print(f"stock_price_close: {stock_price_close}")

# positive means undervalued, negative means overvalued
expected_gain_loss = fair_sharePrice/stock_price_close-1
expected_gain_loss = "{:.0%}".format(expected_gain_loss)
expected_gain_loss
print(f"expected_gain_loss: {expected_gain_loss}")

COE: 0.0798
fair_sharePrice: 17.61
stock_price_close: 28.4
expected_gain_loss: -38%